node:
  name: tyo01-jp
  tier: 1
  region: 1
  node_id: 6
  node_token: "63f4"
  peering:
    enabled: true
    display_name: Tokyo 01
    subtitle: Provided by Lycheen
    protocol_stack: dual_stack
    endpoint: tyo01-jp.ecs.iyoroy-infra.top
    publickey: Sh62ZCxnEcXyLq49mLP1jF4C2vWKhKMxjtZHxVUAQg4=
    listen_port_policy:
      mode: asn_suffix
      # range:
      #   min: 52000
      #   max: 52999
    exporters:
      wireguard: http://tyo01-jp.intra.iyoroy-infra.top:9586/metrics
      bird: http://tyo01-jp.intra.iyoroy-infra.top:9324/metrics
      node: http://tyo01-jp.intra.iyoroy-infra.top:9100/metrics
deploy:
  service_manager: systemd
  bird:
    enabled: true
  wireguard:
    enabled: true
