node:
  name: fra01-de
  tier: 1
  region: 2
  node_id: 1
  node_token: "3b06"
  peering:
    enabled: true
    display_name: Frankfurt 01
    subtitle: Provided by Vultr
    protocol_stack: dual_stack
    endpoint: fra01-de.ecs.iyoroy-infra.top
    publickey: 4zEFOrqHdIDPcjvu6NwbE1AAYBH1bA+SAowysX5fRT4=
    listen_port_policy:
      mode: asn_suffix
    exporters:
      wireguard: http://fra01-de.intra.iyoroy-infra.top:9586/metrics
      bird: http://fra01-de.intra.iyoroy-infra.top:9324/metrics
      node: http://fra01-de.intra.iyoroy-infra.top:9100/metrics
deploy:
  service_manager: systemd
  bird:
    enabled: true
  wireguard:
    enabled: true
