node:
  name: lax01-us
  tier: 1
  region: 4
  node_id: 1
  node_token: "de75"
  peering:
    enabled: true
    display_name: Los Angeles 01
    subtitle: Provided by VMISS
    protocol_stack: dual_stack
    endpoint: lax01-us.ecs.iyoroy-infra.top 
    publickey: As0rZo5b9Bwt4loPGl6iSdtOqkd2p6ExK/Xyoy9OmTU=
    listen_port_policy:
      mode: asn_suffix
      # range:
      #   min: 52000
      #   max: 52999
    exporters:
      wireguard: http://lax01-us.intra.iyoroy-infra.top:9586/metrics
      bird: http://lax01-us.intra.iyoroy-infra.top:9324/metrics
      node: http://lax01-us.intra.iyoroy-infra.top:9100/metrics
deploy:
  service_manager: systemd
  bird:
    enabled: true
  wireguard:
    enabled: true
